language: java
jdk:
  - openjdk8
services:
  - docker
branches:
  only:
    - master
env:
  - MONGO_DATABASE=vulcano
  - MONGO_PASSWORD=NSaHRQpoojcFIDqj
  - MONGO_SRV="cluster0-uwcs4.mongodb.net"
  - MONGO_USER=spock
deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_API_KEY
  app: vulcano-main