language: java
jdk:
- openjdk8
services:
- docker
branches:
  only:
  - master
deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: vjeWrQ5d8OOFvvxFY7Mel9dKCJgyMnwUNBH5spD74rIjTW0sBLuZCr6+fLqfyDibMsdYs5nJbALiF44jBQvF698SGxGk0EqbhsDYgLmFhfZmlvY7BslvEoB+mi+vpBJHOSqCZ7dokAw7b8lXJj9BndEMVSE6mYF09ik/SCm72OoMnH+AjGD6Y37as052xFBM4uWYAseuT6vsagP9+RVlUyrEVLl/oMYRREyWVtEpAgVbBycG/mK29Nbv8EucjneGzDDL1UfWXqody7rf31KT+fwM16T9quZ6CCcNV5PRS9jJ5Pky/sL+jVrvVD+XiCMCepbvZe/aCEmErQu3cAwVO29yik2mVCYzAvChUWb8A9DPSIfmeHu+xDi5IjL1a8lj2/T/kS/Xp/9YBs2LAdCAIr3h+zCpFpyf4wTvJDFwoU0WXdp9PRaPPRNDNkL5ShCpxcau3N7J1CNC1gGj6kLRGB5sC0OW42lZsTNIdeS8MqdYUEuDuwfJbhS8Rv1upOh0W/8dL1S4GodEVq82pFrz6uWb3675deFMXc2ARQLCM/5XNUX+pqcfYvEkXPOVrn+KnQO+i4WYdb2XYwaJMl4lcoiL0qzdJFNzutxfEqnhiF1DvbbJ1MxqWgO6pttMZyHvCNx4MQ98/Sn5KTo4m4zhyHDz2yOHIHjexpio4oopcJQ=
  app: vulcano-main
