language: java
jdk:
- openjdk8
services:
- docker
branches:
  only:
  - master
deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: TndqMkXbfqIN/BLykAjpudfTyisDKEyhLNiMa32n4zDctPvMdV8BPlDM5O36s3RUUeiwLH6RNqN8I266u8LdHuVUXYAZCr2B0T2P7rf10N5ZNAAyKekJ9qkIjiRC9Su8R9qK6ZObVEcaMLyjOqZRhD7KY6E0MPyA4Qgcz1IsxVn9Bx13DQuGQCadRZKhxUbQEtDb1BY9/RXGKZSOdIfyfQchby4AyjBNLcJrAvqRAbXrtcIwAmTr/bLTnnMlH4Kl8iHDv7ZWNwL2mLrt0gGxUzBXSBeTWDoqY5lI3kZM1c0meSWf30Q31zBE9zGkwx7Qfc428Rn0eCfgMnZDA3NU5ojlKpCZeWkAP/GlBOQuegTI7XhhJqXkInKWOvnTh4MNQSZmH0pybGw2CPxlJ7qiRxn7X4RncoxnQ7wRSQA1rSmp3NuXs4HCDEyPQ6NlIiEeHUAtl4huUmNaWiBBzx9ap9BbPRuSiAjsOm7GjzlCWlLfRg36PAUg/yXS7lTMMaS+Z3kG/7+vY74VqNjFFYez2QaLqa68uzIw3mY0OYSC9ejaGvCAxVX7jALN7ZfCnjdSquC701HqZ6rChy6Gtl7LjKHltGiGQV5Z4huIZ1NgDb+HA2kz354bRNlsyqcKgwNY/8FVdgjK2Ku9/hfd9U9RpUlVkE7U4xIrQTs770llbTA=
  app: vulcano-main
