language: java
jdk:
  - openjdk8
services:
  - docker
before_install:
  - docker build -t pronostico-loco --build-arg MONGO_DATABASE=$MONGO_DATABASE --build-arg MONGO_USER=$MONGO_USER --build-arg MONGO_SRV=$MONGO_SRV --build-arg MONGO_PASSWORD=$MONGO_PASSWORD .
branches:
  only:
    - master
deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_API_KEY
  app: vulcano-main