language: java
jdk:
- openjdk8
services:
- docker
branches:
  only:
  - master
deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: lqJUj3eZz0s8r+UnwBFPLLEAvEk8lxgaF4ciydKwvUHDMggyRnJZ0BisWGHJv9j71V6ls+ZiN+cajmfMl4wieoKjD7BHmQIFbnVupofyD1ELvKT1SeHpzrNPJGbv2FtyuwC3j43qMMOMC3baO7U7BLpUeB2liDiYzUPEFQLRE/ojRPYa7DnGe8wu/rm4wnbsVUmKV4HMrp/IbNpjDTAtTUz568plAOJs3fOv/K5BucQuSN6EWPFz3MNAb7314yWyXvIZl+OSaDmr07R+aRPMeqY/cUUiW/MBut4eRGzV1f0mfZxM24+OgiCCDRsMmDSOqyFKQ4edz90BlCMVaf7w3b5gZW1Jcl3DjrTBuKtAcbPWCPbUn3TmPQbH6VQ9jTevMlKhOiaIA6wVi3laJ+zW8evlMuXFLXpi3JqT0KrhiXCRZtzEcaUnqZypDW8PFk9RNGxZlTE2sLaWp+lwu24TOFYzbBzcKfJNiSzkM8AmqqXg2+K9Tb6aG2vPvJOk8hVTk/BXKa2epW9qlp9aGYQ1GgzHT7jG7ITn0UdLnTDucsMw46YlTtW4NR4XPFb0Fa/wKgyWvGGMsMrmSI7FZ9Is7lZezY6Q8eRc41Orokz/fotRRqxZ2p2r5hMffmoIZ4scnRanHzLFiX/2/5aOP3OgsRKwDZREbwwGkNcIQ4ExvxI=
  app: vulcano-main
