language: java
jdk:
- openjdk8
services:
- docker
branches:
  only:
  - master
deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: hhuKnrLkbABvi9G6/ky/SrSih37ohuiBVwYxBA6KChXgz3fICyMFFXzX2vsdQ7Jt0L2CgYb3cLiB80KKRirODnoWTQA2fMfBDVNAyNUx4ealtL2DDidXKGA2K88eD5YKvkDPVL33QaBDqbrnQLogvJAKjvD/nzOQjw30dvEXpTaufTEjjJBQscYQZI93Cq9FkT9TrgktWIoHo9k6uMkZnfun4JBQmhhqfgcD+XL6fKuAEfoaVcc5PjyW9gmfiZ4lKb63P/NixHvT53L6Cw2hieE6iOvxw53LZe4+GrzSzIV+AvgKn1Xo323bSJeMAEZ+2M44o/U2rISFWbTTxy+2CwW0pzQjCxBzz2Ry/tj9StY1TNIuljczY93WxvOJYE+Q88aYk05EvMxBfNsgBnN1oJHeYhEfZ8JvuDmJ+FU9LtS6FAU8TfXrTB+fgW7lDIFXEZfhvVVhEGyq6A0RjSpORc8490CUeGA/vgbfD6k8mZE9YznNeoiwoFmBWSKmmhyZ8VChwLQwI1v2ZQUNbg3IeNcPde+bs4nois//YxPWvOulrXZjyasx7Q3+KZERmXHi/oQiQ57pQ0ryqXB/p8VU4gUZL9DQ5zeL/tLC0evgQbYtEGHMe4fA2HAEqPBQ3qEJbJ+e6sC5SSH0HmXyd71fLqlaLP27wma1nn5pL7A6fow=
  app: vulcano-main
